---
name: firmitas
on: [push, pull_request, workflow_dispatch]
jobs:
  ci-basic:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the base dependencies
        run: |
             python3 -m pip install --upgrade poetry tox

      - name: Check the correctness of the project config
        run: |
           poetry check

      - name: Check the quality of the code
        run: |
             tox -e cleaning

  ci-tests:
    strategy:
      fail-fast: false
      matrix:
        tox-env: ["py38", "py39", "py310", "py311", "py312", "py313"]
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the base dependencies
        run: |
             python3 -m pip install --upgrade tox

      - name: Set up user for running the testcases
        run: |
             useradd testrunner
             chown -R testrunner .

      - name: Execute tox
        run: |
             su testrunner -c "tox -e ${{ matrix.tox-env }}"
        env:
          FIRMITAS_TEST_USERNAME: "${{ secrets.FIRMITAS_TEST_USERNAME }}"
          FIRMITAS_TEST_PASSWORD: "${{ secrets.FIRMITAS_TEST_PASSWORD }}"
          FIRMITAS_TEST_REPONAME: "${{ secrets.FIRMITAS_TEST_REPONAME }}"
